### ISSUE TITLE
Considering being framework agnostic

### ISSUE THREAD

**Issue by ptondereau** [hoymultimedia/PHP-Caspeco#9]
The title speaks for itself :) 

What do you think ?

**Comment by vinkla** [comment]
How do you mean? Maybe you could explain a bit more?

**Comment by ptondereau** [comment]
For now, your package use Laravel but I think you could provide a lower PHP lib. It'll aim to let user choose its HTTP client (PSR-7) and can be pluggable to any ContainerInterface (https://github.com/container-interop/container-interop)

**Comment by vinkla** [comment]
It isn't up to me any longer to make these kinds of decisions since I'm of the project. Though, I think the maintainers don't care about this right now. The library works for their use case and probably wont be spending anytime updating the package.

Thanks for suggesting it though!

**Comment by vinkla** [comment]
It isn't up to me any longer to make these kinds of decisions since I'm of the project. Though, I think the maintainers don't care about this right now. The library works for their use case and probably wont be spending anytime updating the package.

Thanks for suggesting it though!

**Comment by vinkla** [comment]
It isn't up to me any longer to make these kinds of decisions since I'm of the project. Though, I think the maintainers don't care about this right now. The library works for their use case and probably wont be spending anytime updating the package.

Thanks for suggesting it though!

**Comment by ptondereau** [comment]
And maybe ServiceProvider aware (https://github.com/container-interop/service-provider)

**Comment by ptondereau** [comment]
And maybe ServiceProvider aware (https://github.com/container-interop/service-provider)

**Comment by ptondereau** [comment]
And maybe ServiceProvider aware (https://github.com/container-interop/service-provider)

**Comment by ptondereau** [comment]
And maybe ServiceProvider aware (https://github.com/container-interop/service-provider)

**Comment by ptondereau** [comment]
And maybe ServiceProvider aware (https://github.com/container-interop/service-provider)

**Comment by ptondereau** [comment]
I understand but I'm up to make it happen if they really care.

**Comment by vinkla** [comment]
@ptondereau are you using their service?

**Comment by ptondereau** [comment]
nop

**Comment by vinkla** [comment]
Just talked to the maintainers and they wont merge any pull requests. Sorry. Thanks for showing interest though!

**Comment by ptondereau** [comment]
thanks :/
